#ifndef LEDMATRIX_CONFIG_H
#define LEDMATRIX_CONFIG_H


/* Please write pin pair PORT,PIN*/
#define LEDMATRIX_ROW0	    GPIOA,PIN4
#define LEDMATRIX_ROW1		GPIOA,PIN5
#define LEDMATRIX_ROW2      GPIOA,PIN6
#define LEDMATRIX_ROW3      GPIOA,PIN7
#define LEDMATRIX_ROW4      GPIOA,PIN8
#define LEDMATRIX_ROW5      GPIOA,PIN9
#define LEDMATRIX_ROW6      GPIOA,PIN10
#define LEDMATRIX_ROW7      GPIOA,PIN11

#define LEDMATRIX_COL0		GPIOB,PIN8
#define LEDMATRIX_COL1		GPIOB,PIN9
#define LEDMATRIX_COL2      GPIOB,PIN10
#define LEDMATRIX_COL3      GPIOB,PIN11
#define LEDMATRIX_COL4      GPIOB,PIN12
#define LEDMATRIX_COL5      GPIOB,PIN13
#define LEDMATRIX_COL6      GPIOB,PIN14
#define LEDMATRIX_COL7      GPIOB,PIN15


#endif
